id: I21A40529
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.002415
last_modified: 2023-02-09 14:46:46.002832
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: sa
bases:
  897C:
    base_file: 897C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
